# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc

class Ui_Igate(object):
    def setupUi(self, Igate):
        Igate.setObjectName("Igate")
        Igate.setWindowModality(QtCore.Qt.WindowModal)
        Igate.resize(805, 645)
        font = QtGui.QFont()
        font.setPointSize(7)
        Igate.setFont(font)
        Igate.setLayoutDirection(QtCore.Qt.LeftToRight)
        Igate.setAutoFillBackground(True)
        Igate.setStyleSheet("")
        Igate.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Igate)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(-150, -180, 1191, 901))
        self.listView.setStyleSheet("background-image: url(:/cat.png);")
        self.listView.setObjectName("listView")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(390, 140, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-image: url(:/bkgbutton.png);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 420, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-image: url(:/bkgbutton.png);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(580, 430, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-image: url(:/bkgbutton.png);")
        self.pushButton_7.setObjectName("pushButton_7")
        Igate.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Igate)
        self.statusbar.setObjectName("statusbar")
        Igate.setStatusBar(self.statusbar)

        self.retranslateUi(Igate)
        QtCore.QMetaObject.connectSlotsByName(Igate)

    def retranslateUi(self, Igate):
        _translate = QtCore.QCoreApplication.translate
        Igate.setWindowTitle(_translate("Igate", "Welcome Home!"))
        self.pushButton_5.setText(_translate("Igate", "Admin"))
        self.pushButton_6.setText(_translate("Igate", "I\'m back!"))
        self.pushButton_7.setText(_translate("Igate", "I\'m new!"))

from PyQt5 import uic
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys

class MyWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        uic.loadUi('frontpage.ui', self)

app = QApplication(sys.argv)
window = MyWindow()
window.show()
sys.exit(app.exec_())